### ISSUE TITLE
Is possible pass safety_settings through openAI SDK to gemini?

### ISSUE THREAD

**Issue by zhangzhenxi** [google/generative-ai-go#237] opened 2024-12-18 11:28 UTC
### Description of the feature request:

Is it possible to transmit safety_settings parameters through the OpenAI SDK for integration with Gemini?

something like:

```golang
client := openai.NewClient(openaiOption.WithBaseURL("https://generativelanguage.googleapis.com/v1beta/openai"), openaiOption.WithAPIKey("xxx"))
completion, err := client.Chat.Completions.New(context.TODO(), openai.ChatCompletionNewParams{
	Messages: openai.F([]openai.ChatCompletionMessageParamUnion{openai.ChatCompletionUserMessageParam{
		Role: openai.F(openai.ChatCompletionUserMessageParamRoleUser),
		Content: openai.F([]openai.ChatCompletionContentPartUnionParam{openai.ChatCompletionContentPartTextParam{
			Text: openai.F("prompts"),
			Type: openai.F(openai.ChatCompletionContentPartTextTypeText),
		}}),
	}}),
	Model: openai.F("gemini-1.5-flash"),
},
	openaiOption.WithJSONSet("safety_settings.0.category", 1),
	openaiOption.WithJSONSet("safety_settings.0.threshold", 1),
)
```

**Comment by eliben** [comment] 2024-12-18 16:57
It's not clear to me what this question is about. Is this about the Gemini SDK project this GitHub repository hosts?

**Comment by zhangzhenxi** [comment] 2024-12-18 17:26
Theoretically, this is not related to the project. I just thought that you might be more familiar with the Gemini API, so perhaps you could find an answer here. If I have disturbed you, please accept my sincere apologies.

**Comment by eliben** [comment] 2024-12-18 17:33
I'm closing this issue. I think this forum https://discuss.ai.google.dev/ may be a good place for your question, which is about the underlying Gemini API, as far as I understand.

Generally, your question is at the intersection of the Gemini API and the OpenAI SDK. I would recommend experimenting with sending direct HTTP requests (e.g. with `curl`) to the API first to get a better understanding of where the issue is.

**Closed by eliben** 2024-12-18 17:33 UTC
Labels: type:feature request, status:awaiting user response

**Comment by zhangzhenxi** [comment] 2024-12-18 17:37
Thanks.
