### ISSUE TITLE
proto: (line 34:3): unknown field "usageMetadata"

### ISSUE THREAD

**Issue by jlcheng** [google/generative-ai-go#97] opened 2024-05-02 21:43 UTC
### Description of the bug:

When using the StartChat() and SendMessage() API, one gets the "proto: (line 34:3): unknown field "usageMetadata"
" error.

You can reproduce the problem with:
```
package main

import (
	"context"
	"fmt"
	"log"
	"os"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"
)

func main() {
	ctx := context.Background()
	client, err := genai.NewClient(ctx, option.WithAPIKey(os.Getenv("GEMINI_API_KEY")))
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()
	model := client.GenerativeModel("gemini-1.0-pro")
	cs := model.StartChat()

	msg := "hello"
	fmt.Printf("== Me: %s\n== Model:\n", msg)
	_, err = cs.SendMessage(ctx, genai.Text(msg))
	if err != nil {
		log.Fatal(err)
	}
}
```

### Actual vs expected behavior:

Actual behavior: 
The SDK returns an error

Expected behavior:
No errors from the SDK.

### Any other information you'd like to share?

Maybe the underlying problem has to do with a new field added to https://github.com/googleapis/googleapis/blob/master/google/ai/generativelanguage/v1beta/generative_service.proto?

The error message suggests it may be a new field named "usageMetadata" on the "GenerateContentResponse" message. I don't see it referenced in the generative_service.proto, so maybe it's not published yet? I am reporting it here mainly because it surfaced through the Go SDK.

**Comment by jmzwcn** [comment] 2024-05-03 00:25
yes, it is a new bug nearlyl

**Comment by charieswei** [comment] 2024-05-03 03:02
Expect the authorities to fix this issue soon

**Comment by vgjm** [comment] 2024-05-03 04:36
I met the same problem.

**Comment by kkdai** [comment] 2024-05-03 04:46
v0.5.0 to v0.11.0 also reproduce this.

**Comment by mattthewong** [comment] 2024-05-03 06:28
Same here.

**Comment by aicoder01** [comment] 2024-05-03 07:21
same problem.

**Comment by jba** [comment] 2024-05-03 13:14
Thanks everyone, we're working on a fix.

**Comment by Mersanko** [comment] 2024-05-03 15:19
currently experiencing the same issue.

**Comment by jba** [comment] 2024-05-03 15:22
@douglarek Good point, I should not have written "Fixes" in the PR.
I've now pushed the v0.11.1 tag. 
Please update your projects with `go get github.com/google/generative-ai-go@v0.11.1`.

**Comment by jba** [comment] 2024-05-03 15:23
First person to report success gets to close the issue!

**Comment by jba** [comment] 2024-05-03 15:25
> Seriously, this is so frustrating.

@douglarek, I totally agree. But this cuts across languages. It's an issue with the underlying service, and trust me, Google is taking this _very_ seriously.

**Comment by nayyara-airlangga** [comment] 2024-05-03 15:38
@jba just tested the fix using different prompts. It all works fine now. Nice idea on future-proofing for unknown fields from upstream

**Closed** 2024-05-03 16:01 UTC
Labels: type:bug

**Comment by jlcheng** [comment] 2024-05-03 17:53
FWIW, the Go program I used no longer has this error **even without recompiling the code**. It is possible that something upstream changed as well. Regardless, I can no longer reproduce the problem. Many thanks for everyone who helped fix this!

**Comment by jba** [comment] 2024-05-03 19:26
Yes, the problem was eventually fixed server-side.
